### ISSUE TITLE
Wrong lines 

### ISSUE THREAD

**Issue by mystycs** [learn-co-curriculum/oo-basics-with-class-constants#6]
It says below in the middle of the assignment From lines 41-52, but 01_book_spec.rb only has 15 lines. I think it should say Lines 2-13

"I really have no clue how in the world my array would magically contain "Thriller", so let's look at the specific test to figure out what's going on. From lines 41-52 in spec/01_book_spec.rb:"

**Comment by AnnJohn** [comment]
Hi @mystycs thanks for pointing this out. We updated the specs!
