### ISSUE TITLE
Repeats a lot of material from oo-basics

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/oo-basics-with-class-constants#8]
https://github.com/learn-co-curriculum/oo-basics

A bunch of this stuff is just copy-pasted.

**Comment by alexgriff** [comment]
@pletcher Should I be assuming that this lab will always be done following oo-basics, or should it be able to stand alone? As a student I do vaguely remember some weirdness happening around this lab, the only one I have forked on my computer is the -with-class-constants version, but sort of remember doing the other version and then only keeping one.

**Comment by pletcher** [comment]
I think we can assume that it'll always be done with oo-basics. I guess the question is, as a student, did you find the repetition helpful? Or should one of these labs be cut (or substantially rewritten)?

**Comment by alexgriff** [comment]
@pletcher I did some rewriting, is it ok to reference the other lab as I do? I also pushed to the solution branch first.  Not sure about the proper workflow here.

**Comment by pletcher** [comment]
I added some comments on the PR -- very minor stuff before it's ready to go!

It's totally cool to push solution first -- generally, the solution branch is just kind of there (and of course passes the tests).
